from enum import StrEnum


class AccountType(StrEnum):
    ASSET = "ASSET"
    LIABILITY = "LIABILITY"
    EQUITY = "EQUITY"
    REVENUE = "REVENUE"
    EXPENSE = "EXPENSE"


class NormalBalance(StrEnum):
    DEBIT = "DEBIT"
    CREDIT = "CREDIT"


class AccountKey(StrEnum):
    CASH = "CASH"
    BANK = "BANK"
    DIGITAL_WALLET = "DIGITAL_WALLET"
    RECEIVABLE = "RECEIVABLE"
    INVENTORY = "INVENTORY"
    EQUIPMENT = "EQUIPMENT"
    PAYABLE = "PAYABLE"
    OTHER_PAYABLE = "OTHER_PAYABLE"
    OWNER_CAPITAL = "OWNER_CAPITAL"
    OWNER_DRAW = "OWNER_DRAW"
    RETAINED_EARNINGS = "RETAINED_EARNINGS"
    SALES = "SALES"
    SERVICE_REVENUE = "SERVICE_REVENUE"
    OTHER_REVENUE = "OTHER_REVENUE"
    PURCHASES = "PURCHASES"
    RAW_MATERIALS = "RAW_MATERIALS"
    TRANSPORTATION = "TRANSPORTATION"
    ELECTRICITY = "ELECTRICITY"
    INTERNET = "INTERNET"
    SALARY = "SALARY"
    RENT = "RENT"
    PROMOTION = "PROMOTION"
    ADMINISTRATION = "ADMINISTRATION"
    OTHER_EXPENSE = "OTHER_EXPENSE"


class TransactionType(StrEnum):
    CASH_SALE = "CASH_SALE"
    NON_CASH_SALE = "NON_CASH_SALE"
    CREDIT_SALE = "CREDIT_SALE"
    CASH_PURCHASE = "CASH_PURCHASE"
    CREDIT_PURCHASE = "CREDIT_PURCHASE"
    CAPITAL_CONTRIBUTION = "CAPITAL_CONTRIBUTION"
    OWNER_DRAW = "OWNER_DRAW"
    PAYABLE_PAYMENT = "PAYABLE_PAYMENT"
    RECEIVABLE_RECEIPT = "RECEIVABLE_RECEIPT"
    OPERATING_EXPENSE = "OPERATING_EXPENSE"


POSTED_TRANSACTION_TYPES = (*tuple(item.value for item in TransactionType), "REVERSAL")

EXPENSE_ACCOUNT_KEYS = frozenset(
    {
        AccountKey.PURCHASES,
        AccountKey.RAW_MATERIALS,
        AccountKey.TRANSPORTATION,
        AccountKey.ELECTRICITY,
        AccountKey.INTERNET,
        AccountKey.SALARY,
        AccountKey.RENT,
        AccountKey.PROMOTION,
        AccountKey.ADMINISTRATION,
        AccountKey.OTHER_EXPENSE,
    }
)

INCOME_ACCOUNT_KEYS = frozenset(
    {
        AccountKey.SALES,
        AccountKey.SERVICE_REVENUE,
        AccountKey.OTHER_REVENUE,
    }
)

PURCHASE_TARGET_KEYS = EXPENSE_ACCOUNT_KEYS | {AccountKey.INVENTORY}
NON_CASH_ACCOUNT_KEYS = frozenset({AccountKey.BANK, AccountKey.DIGITAL_WALLET})
OPERATING_PAYMENT_KEYS = frozenset({AccountKey.CASH, AccountKey.BANK})
