-- Financial integrity smoke tests for KASTA PostgreSQL.
--
-- Execute as the database owner against a disposable/CI database.  All
-- fixture writes are rolled back.  The script checks both existing data and
-- the immutable/reversal/financial journal triggers installed by the
-- accounting and security migrations.  It never deletes or updates a real record.

\set ON_ERROR_STOP on

BEGIN;

-- A clean migration database has no business data yet.  Create a deterministic
-- synthetic tenant so the mutation and constraint checks below are never
-- silently skipped.  The enclosing transaction rolls these rows back.
INSERT INTO organizations (id, name, status)
VALUES ('00000000-0000-0000-0000-0000000000f1', 'QA Integrity Organization', 'ACTIVE');
INSERT INTO users (id, email, password_hash, full_name, status, email_verified_at)
VALUES ('00000000-0000-0000-0000-0000000000f1', 'qa-integrity@example.invalid', 'qa-only', 'QA Integrity User', 'ACTIVE', now());
INSERT INTO businesses (id, organization_id, code, name, status)
VALUES ('00000000-0000-0000-0000-0000000000f1', '00000000-0000-0000-0000-0000000000f1', 'QA-INTEGRITY', 'QA Integrity Business', 'ACTIVE');
INSERT INTO business_members (id, business_id, user_id, role_id, status, joined_at)
SELECT '00000000-0000-0000-0000-0000000000f1',
       '00000000-0000-0000-0000-0000000000f1',
       '00000000-0000-0000-0000-0000000000f1',
       id, 'ACTIVE', now()
  FROM roles WHERE code = 'business_owner';

DO $$
DECLARE
    bad_count bigint;
BEGIN
    -- Header totals must agree with each other.
    SELECT count(*) INTO bad_count
      FROM journal_entries
     WHERE total_debit <> total_credit;
    IF bad_count > 0 THEN
        RAISE EXCEPTION '% journal headers are unbalanced', bad_count;
    END IF;

    -- The deferred trigger also enforces this at write time; this query gives
    -- a useful diagnostic for data restored from an older backup.
    SELECT count(*) INTO bad_count
      FROM (
            SELECT e.id,
                   e.total_debit,
                   e.total_credit,
                   count(l.id) AS line_count,
                   coalesce(sum(l.debit_amount), 0) AS line_debit,
                   coalesce(sum(l.credit_amount), 0) AS line_credit
              FROM journal_entries e
              LEFT JOIN journal_lines l ON l.journal_entry_id = e.id
             GROUP BY e.id, e.total_debit, e.total_credit
           ) q
     WHERE q.line_count < 2
        OR q.line_debit <= 0
        OR q.line_debit <> q.line_credit
        OR q.line_debit <> q.total_debit
        OR q.line_credit <> q.total_credit;
    IF bad_count > 0 THEN
        RAISE EXCEPTION '% journal entries have invalid line totals', bad_count;
    END IF;

    -- Every posted/reversed financial transaction has one journal entry.
    SELECT count(*) INTO bad_count
      FROM transactions t
      LEFT JOIN journal_entries e ON e.transaction_id = t.id
     WHERE e.id IS NULL;
    IF bad_count > 0 THEN
        RAISE EXCEPTION '% financial transactions have no journal entry', bad_count;
    END IF;
END
$$;

DO $$
DECLARE
    business_id uuid;
    user_id uuid;
    cash_account uuid;
    capital_account uuid;
    transaction_id uuid := gen_random_uuid();
    entry_id uuid := gen_random_uuid();
    line_debit_id uuid := gen_random_uuid();
    line_credit_id uuid := gen_random_uuid();
    audit_id uuid := gen_random_uuid();
BEGIN
    SELECT b.id INTO business_id FROM businesses b ORDER BY b.created_at, b.id LIMIT 1;
    SELECT u.id INTO user_id FROM users u ORDER BY u.created_at, u.id LIMIT 1;
    IF business_id IS NULL OR user_id IS NULL THEN
        RAISE NOTICE 'No business/user fixture exists; mutation checks skipped';
        RETURN;
    END IF;

    -- Use two temporary system accounts.  UUIDs are generated by PostgreSQL;
    -- all rows disappear with the outer ROLLBACK.
    cash_account := gen_random_uuid();
    capital_account := gen_random_uuid();
    INSERT INTO accounts (
        id, business_id, code, name, account_type, normal_balance, is_system, is_active
    ) VALUES
        (cash_account, business_id, 'QA-' || substr(cash_account::text, 1, 8), 'QA Cash', 'ASSET', 'DEBIT', false, true),
        (capital_account, business_id, 'QA-' || substr(capital_account::text, 1, 8), 'QA Capital', 'EQUITY', 'CREDIT', false, true);

    INSERT INTO transactions (
        id, business_id, transaction_number, transaction_type, transaction_date,
        amount, description, status, revision_number, posted_at, posted_by_user_id
    ) VALUES (
        transaction_id, business_id, 'QA-' || substr(transaction_id::text, 1, 8),
        'CAPITAL_CONTRIBUTION', current_date, 100.00, 'QA financial integrity fixture',
        'POSTED', 1, now(), user_id
    );

    INSERT INTO journal_entries (
        id, business_id, transaction_id, entry_number, entry_date, description,
        source, status, total_debit, total_credit, posted_at, posted_by_user_id
    ) VALUES (
        entry_id, business_id, transaction_id, 'QA-' || substr(entry_id::text, 1, 8),
        current_date, 'QA financial integrity fixture', 'CAPITAL_CONTRIBUTION',
        'POSTED', 100.00, 100.00, now(), user_id
    );

    INSERT INTO journal_lines (
        id, business_id, journal_entry_id, account_id, description, debit_amount, credit_amount
    ) VALUES
        (line_debit_id, business_id, entry_id, cash_account, 'QA debit', 100.00, 0.00),
        (line_credit_id, business_id, entry_id, capital_account, 'QA credit', 0.00, 100.00);

    -- Force the DEFERRABLE balance trigger now instead of waiting for the
    -- outer rollback.  A valid two-line journal must pass the same check used
    -- at commit time in production.
    SET CONSTRAINTS trg_journal_entries_balanced, trg_journal_lines_balanced IMMEDIATE;

    -- Posted transaction content cannot be edited; reversal is the supported
    -- path.  Nested blocks catch and assert the trigger error without aborting
    -- the outer fixture transaction.
    BEGIN
        UPDATE transactions SET description = 'tampered' WHERE id = transaction_id;
        RAISE EXCEPTION 'posted transaction content update unexpectedly succeeded';
    EXCEPTION WHEN raise_exception THEN
        IF SQLERRM = 'posted transaction content update unexpectedly succeeded' THEN
            RAISE;
        END IF;
    END;

    BEGIN
        DELETE FROM transactions WHERE id = transaction_id;
        RAISE EXCEPTION 'financial transaction delete unexpectedly succeeded';
    EXCEPTION WHEN raise_exception THEN
        IF SQLERRM = 'financial transaction delete unexpectedly succeeded' THEN
            RAISE;
        END IF;
    END;

    BEGIN
        UPDATE journal_lines SET debit_amount = 99.00 WHERE id = line_debit_id;
        RAISE EXCEPTION 'journal line update unexpectedly succeeded';
    EXCEPTION WHEN raise_exception THEN
        IF SQLERRM = 'journal line update unexpectedly succeeded' THEN
            RAISE;
        END IF;
    END;

    -- Audit records are append-only as well.
    INSERT INTO audit_logs (
        id, business_id, actor_user_id, action, entity_type, entity_id, reason, created_at
    ) VALUES (
        audit_id, business_id, user_id, 'QA_INTEGRITY', 'TRANSACTION', transaction_id,
        'QA fixture', now()
    );
    BEGIN
        UPDATE audit_logs SET reason = 'tampered' WHERE id = audit_id;
        RAISE EXCEPTION 'audit update unexpectedly succeeded';
    EXCEPTION WHEN insufficient_privilege THEN
        NULL;
        WHEN raise_exception THEN
        IF SQLERRM = 'audit update unexpectedly succeeded' THEN
            RAISE;
        END IF;
    END;
    BEGIN
        DELETE FROM audit_logs WHERE id = audit_id;
        RAISE EXCEPTION 'audit delete unexpectedly succeeded';
    EXCEPTION WHEN insufficient_privilege THEN
        NULL;
        WHEN raise_exception THEN
        IF SQLERRM = 'audit delete unexpectedly succeeded' THEN
            RAISE;
        END IF;
    END;
END
$$;

-- Check constraints reject a header that is not balanced.  The error is
-- deliberately handled in a subtransaction so the rest of the smoke test can
-- complete.
DO $$
DECLARE
    business_id uuid;
    invalid_entry_id uuid := gen_random_uuid();
BEGIN
    SELECT id INTO business_id FROM businesses ORDER BY created_at, id LIMIT 1;
    IF business_id IS NULL THEN
        RAISE NOTICE 'No business fixture exists; unbalanced-header check skipped';
        RETURN;
    END IF;
    BEGIN
        INSERT INTO journal_entries (
            id, business_id, entry_number, entry_date, description, source,
            status, total_debit, total_credit, posted_at
        ) VALUES (
            invalid_entry_id, business_id, 'QA-INVALID-' || substr(invalid_entry_id::text, 1, 8),
            current_date, 'Should fail', 'QA', 'POSTED', 10.00, 9.00, now()
        );
        RAISE EXCEPTION 'unbalanced journal header unexpectedly succeeded';
    EXCEPTION WHEN check_violation THEN
        NULL;
    END;
END
$$;

ROLLBACK;

\echo 'Financial integrity smoke tests passed; fixture transaction rolled back.'
